### ISSUE TITLE
Error on manually trigger beautify_select

### ISSUE THREAD

**Issue by mourtazag** [SmashingQuasar/beautified-select#6]
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at bs.js:347
    at NodeList.forEach (<anonymous>)
    at HTMLDocument.<anonymous> (bs.js:339)

**Comment by SmashingQuasar** [comment]
Was due to a select inside a <beautified-select> which hadn't been beautified. Resolved in commit d7711fdb38b24f6408c359682dd396bab8c46b52
